# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspace/teapot-libcheckpoint_x64

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspace/teapot-libcheckpoint_x64

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/teapot-libcheckpoint_x64/CMakeFiles /workspace/teapot-libcheckpoint_x64/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspace/teapot-libcheckpoint_x64/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named checkpoint_x64_nonest

# Build rule for target.
checkpoint_x64_nonest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkpoint_x64_nonest
.PHONY : checkpoint_x64_nonest

# fast build rule for target.
checkpoint_x64_nonest/fast:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/build
.PHONY : checkpoint_x64_nonest/fast

#=============================================================================
# Target rules for targets named checkpoint_x64

# Build rule for target.
checkpoint_x64: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 checkpoint_x64
.PHONY : checkpoint_x64

# fast build rule for target.
checkpoint_x64/fast:
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/build
.PHONY : checkpoint_x64/fast

checkpoint.o: checkpoint.c.o

.PHONY : checkpoint.o

# target to build an object file
checkpoint.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint.c.o
.PHONY : checkpoint.c.o

checkpoint.i: checkpoint.c.i

.PHONY : checkpoint.i

# target to preprocess a source file
checkpoint.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint.c.i
.PHONY : checkpoint.c.i

checkpoint.s: checkpoint.c.s

.PHONY : checkpoint.s

# target to generate assembly for a file
checkpoint.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint.c.s
.PHONY : checkpoint.c.s

checkpoint_asm.o: checkpoint_asm.c.o

.PHONY : checkpoint_asm.o

# target to build an object file
checkpoint_asm.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint_asm.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint_asm.c.o
.PHONY : checkpoint_asm.c.o

checkpoint_asm.i: checkpoint_asm.c.i

.PHONY : checkpoint_asm.i

# target to preprocess a source file
checkpoint_asm.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint_asm.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint_asm.c.i
.PHONY : checkpoint_asm.c.i

checkpoint_asm.s: checkpoint_asm.c.s

.PHONY : checkpoint_asm.s

# target to generate assembly for a file
checkpoint_asm.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/checkpoint_asm.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/checkpoint_asm.c.s
.PHONY : checkpoint_asm.c.s

dift_support.o: dift_support.c.o

.PHONY : dift_support.o

# target to build an object file
dift_support.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_support.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_support.c.o
.PHONY : dift_support.c.o

dift_support.i: dift_support.c.i

.PHONY : dift_support.i

# target to preprocess a source file
dift_support.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_support.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_support.c.i
.PHONY : dift_support.c.i

dift_support.s: dift_support.c.s

.PHONY : dift_support.s

# target to generate assembly for a file
dift_support.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_support.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_support.c.s
.PHONY : dift_support.c.s

dift_wrappers.o: dift_wrappers.c.o

.PHONY : dift_wrappers.o

# target to build an object file
dift_wrappers.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_wrappers.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_wrappers.c.o
.PHONY : dift_wrappers.c.o

dift_wrappers.i: dift_wrappers.c.i

.PHONY : dift_wrappers.i

# target to preprocess a source file
dift_wrappers.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_wrappers.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_wrappers.c.i
.PHONY : dift_wrappers.c.i

dift_wrappers.s: dift_wrappers.c.s

.PHONY : dift_wrappers.s

# target to generate assembly for a file
dift_wrappers.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/dift_wrappers.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/dift_wrappers.c.s
.PHONY : dift_wrappers.c.s

report_gadget.o: report_gadget.c.o

.PHONY : report_gadget.o

# target to build an object file
report_gadget.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/report_gadget.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/report_gadget.c.o
.PHONY : report_gadget.c.o

report_gadget.i: report_gadget.c.i

.PHONY : report_gadget.i

# target to preprocess a source file
report_gadget.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/report_gadget.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/report_gadget.c.i
.PHONY : report_gadget.c.i

report_gadget.s: report_gadget.c.s

.PHONY : report_gadget.s

# target to generate assembly for a file
report_gadget.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/report_gadget.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/report_gadget.c.s
.PHONY : report_gadget.c.s

signal_handler.o: signal_handler.c.o

.PHONY : signal_handler.o

# target to build an object file
signal_handler.c.o:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/signal_handler.c.o
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/signal_handler.c.o
.PHONY : signal_handler.c.o

signal_handler.i: signal_handler.c.i

.PHONY : signal_handler.i

# target to preprocess a source file
signal_handler.c.i:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/signal_handler.c.i
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/signal_handler.c.i
.PHONY : signal_handler.c.i

signal_handler.s: signal_handler.c.s

.PHONY : signal_handler.s

# target to generate assembly for a file
signal_handler.c.s:
	$(MAKE) -f CMakeFiles/checkpoint_x64_nonest.dir/build.make CMakeFiles/checkpoint_x64_nonest.dir/signal_handler.c.s
	$(MAKE) -f CMakeFiles/checkpoint_x64.dir/build.make CMakeFiles/checkpoint_x64.dir/signal_handler.c.s
.PHONY : signal_handler.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... checkpoint_x64_nonest"
	@echo "... edit_cache"
	@echo "... checkpoint_x64"
	@echo "... checkpoint.o"
	@echo "... checkpoint.i"
	@echo "... checkpoint.s"
	@echo "... checkpoint_asm.o"
	@echo "... checkpoint_asm.i"
	@echo "... checkpoint_asm.s"
	@echo "... dift_support.o"
	@echo "... dift_support.i"
	@echo "... dift_support.s"
	@echo "... dift_wrappers.o"
	@echo "... dift_wrappers.i"
	@echo "... dift_wrappers.s"
	@echo "... report_gadget.o"
	@echo "... report_gadget.i"
	@echo "... report_gadget.s"
	@echo "... signal_handler.o"
	@echo "... signal_handler.i"
	@echo "... signal_handler.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

